#!/bin/bash
set -euo pipefail

# If GRUB2 is used, bli.mod needs to be loaded
EFIVAR="/sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f"

[ -e "$EFIVAR" ] || exit 0

# Read the value of the EFI variable, that contains a header and ends
# with '\0' and make it lowercase
ESP_UUID="$(dd "if=$EFIVAR" bs=2 skip=2 conv=lcase status=none | tr -d '\0')"
DEV="/dev/disk/by-partuuid/${ESP_UUID}"

mkdir -p "$1/esp.mount"
cat > "$1/esp.mount" <<EOF
# Automatically generated by pcr-signature-generator

[Unit]
Description=Mount /boot/efi
After=dev-disk-by\\x2dpartuuid-${ESP_UUID//-/\\x2d}.device

[Mount]
What=$DEV
Where=/boot/efi
Type=vfat
EOF

mkdir -p "$1/systemd-cryptsetup@.service.d"
cat > "$1/systemd-cryptsetup@.service.d/pcr-signature.conf" <<EOF
# Automatically generated by pcr-signature-generator

[Unit]
Description=Import TPM2 crendentials into the initrd
Wants=esp.mount
After=esp.mount
ConditionPathExists=!/run/systemd/pcrlock.json
ConditionPathExists=!/run/systemd/tpm2-pcr-signature.json

[Service]
ExecStartPre=/usr/bin/pcr-signature.sh
EOF
