#!/bin/bash
set -euo pipefail

# If GRUB2 is used, bli.mod needs to be loaded
EFIVAR="/sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f"

[ -e "$EFIVAR" ] || exit 0

# Read the value of the EFI variable, that contains a header and ends
# with '\0' and make it lowercase
ESP_UUID="$(dd "if=$EFIVAR" bs=2 skip=2 conv=lcase status=none | tr -d '\0')"
DEV="/dev/disk/by-partuuid/${ESP_UUID}"

cat > "$1/boot-efi.mount" <<EOF
# Automatically generated by pcr-signature-generator

[Unit]
Description=Mount /boot/efi
After=dev-disk-by\\x2dpartuuid-${ESP_UUID//-/\\x2d}.device

[Mount]
What=$DEV
Where=/boot/efi
Type=vfat
EOF

cat > "$1/pcr-signature.service" <<EOF
# Automatically generated by pcr-signature-generator

[Unit]
Description=Import TPM2 crendentials into the initrd

Wants=boot-efi.mount
After=boot-efi.mount
Wants=cryptsetup-pre.target
Before=cryptsetup-pre.target
ConditionPathExists=!/run/systemd/pcrlock.json
ConditionPathExists=!/run/systemd/tpm2-pcr-signature.json

[Service]
Type=oneshot
ExecStart=/usr/bin/pcr-signature.sh
EOF

mkdir -p "$1/initrd.target.wants"
ln -sr "$1/pcr-signature.service" "$1/initrd.target.wants"
