#!/bin/bash
set -euo pipefail

# For a generator, the first parameter `normal-dir` is not optional
[ -n "$1" ] || { echo "Missing normal-dir parameter"; exit 1; }

# If GRUB2 is used, bli.mod needs to be loaded
EFIVAR="/sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f"

if [ -e "$EFIVAR" ]; then
    # Read the value of the EFI variable, that contains a header and
    # ends with '\0' and make it lowercase
    ESP_UUID="$(dd "if=$EFIVAR" bs=2 skip=2 conv=lcase status=none | tr -d '\0')"
    DEV="/dev/disk/by-partuuid/${ESP_UUID}"
elif [ -e /dev/disk/by-designator/esp ]; then
    DEV="/dev/disk/by-designator/esp"
else
    # The ESP cannot be located, so no sysefi.mount is generated here.
    # pcr-signature.service is not ordered against sysefi.mount either
    # (see the drop-in below), so it will simply find /sysefi empty and
    # do nothing.
    exit 0
fi

cat > "$1/sysefi.mount" <<EOF
# Automatically generated by pcr-signature-generator

[Unit]
Description=ESP (/sysefi)
Conflicts=initrd-switch-root.target
Before=initrd-switch-root.target
DefaultDependencies=false

[Mount]
What=$DEV
Where=/sysefi
Type=vfat
Options=utf8
EOF

# Order pcr-signature.service against the mount unit only when this
# generator is the one that created it.  systemd's gpt-auto-generator
# also provides a sysefi.mount (in the late generator directory, so ours
# takes precedence), but that one has the default dependencies enabled
# and requires systemd-fsck@.service, which is ordered after
# systemd-fsck-root.service and therefore after cryptsetup.target.  A
# Wants=/After=sysefi.mount in pcr-signature.service, that is ordered
# before cryptsetup-pre.target, closes an ordering cycle in that case.
mkdir -p "$1/pcr-signature.service.d"
cat > "$1/pcr-signature.service.d/10-sysefi-mount.conf" <<EOF
# Automatically generated by pcr-signature-generator

[Unit]
Wants=sysefi.mount
After=sysefi.mount
EOF
