#!/bin/bash
set -euo pipefail

# For a generator, the first parameter `normal-dir` is not optional
[ -n "$1" ] || { echo "Missing normal-dir parameter"; exit 1; }

# If GRUB2 is used, bli.mod needs to be loaded
EFIVAR="/sys/firmware/efi/efivars/LoaderDevicePartUUID-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f"

if [ -e "$EFIVAR" ]; then
    # Read the value of the EFI variable, that contains a header and
    # ends with '\0' and make it lowercase
    ESP_UUID="$(dd "if=$EFIVAR" bs=2 skip=2 conv=lcase status=none | tr -d '\0')"
    DEV="/dev/disk/by-partuuid/${ESP_UUID}"
elif [ -e /dev/disk/by-designator/esp ]; then
    DEV="/dev/disk/by-designator/esp"
else
    exit 0
fi

cat > "$1/sysefi.mount" <<EOF
# Automatically generated by pcr-signature-generator

[Unit]
Description=ESP (/sysefi)
Conflicts=initrd-switch-root.target
Before=initrd-switch-root.target
DefaultDependencies=false

[Mount]
What=$DEV
Where=/sysefi
Type=vfat
Options=utf8
EOF
